# Generated by Django 4.2 on 2024-02-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='porfolio',
            new_name='portfolio',
        ),
    ]
